### ISSUE TITLE
Adjust configuration for met to match inflow/outflows

### ISSUE THREAD

**Issue by rqthomas** [FLARE-forecast/FLAREr#85]
here is the flows part

```
flows:
   include_inflow: TRUE
   include_outflow: TRUE
   future_inflow_model: historical_interp
   historical_inflow_model: historical_interp
   local_inflow_directory: drivers/inflow
   future_outflow_model: historical_interp
   historical_outflow_model: historical_interp
   local_outflow_directory: drivers/outflow
   use_ler_vars: FALSE
  ```
  
  met could be
  
  ```
  met:
     future_met_model: gefs-v12/stage2
     historical_met_model: historical_interp # or historical_met_model: gets-v12/stage3
     local_met_directory: drivers/met
     use_ler_vars: FALSE
```
